apiVersion: v1
kind: Service

metadata:
  name: tickethub-backend-service
  namespace: {{ .Values.namespace }}

spec:
  type: {{ .Values.backend.service.type }}

  selector:
    app: tickethub-backend

  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: {{ .Values.backend.service.port }}