apiVersion: v1
kind: Service

metadata:
  name: tickethub-backend-service
  namespace: {{ .Values.namespace }}
  labels:
    app: tickethub-backend

spec:
  type: {{ .Values.backend.service.type }}

  selector:
    app: tickethub-backend

  ports:
    - name: http
      port: {{ .Values.backend.service.port }}
      targetPort: {{ .Values.backend.service.port }}
      protocol: TCP