apiVersion: v1
kind: ConfigMap
metadata:
  name: tickethub-config
  namespace: {{ .Values.namespace }}

data:
  NODE_ENV: {{ .Values.config.NODE_ENV | quote }}
  PORT: {{ .Values.config.PORT | quote }}