apiVersion: v1
kind: Secret
metadata:
  name: tickethub-secret
  namespace: {{ .Values.namespace }}

type: Opaque

stringData:
  JWT_SECRET: {{ .Values.secret.JWT_SECRET | quote }}
  MONGODB_URI: {{ .Values.secret.MONGODB_URI | quote }}