namespace: tickethub
backend:
  replicaCount: 1
  image:
    repository: tickethubacr2026.azurecr.io/tickethub-backend
    tag: 0e67f618e64b77d6d4e87022a1bb88c61f644f5b
    pullPolicy: Always
  service:
    type: ClusterIP
    port: 5000
  resources:
    requests:
      cpu: "100m"
      memory: "128Mi"
    limits:
      cpu: "250m"
      memory: "256Mi"
  probes:
    liveness:
      path: /health
      initialDelaySeconds: 20
      periodSeconds: 10
    readiness:
      path: /health
      initialDelaySeconds: 10
      periodSeconds: 5
frontend:
  replicaCount: 1
  image:
    repository: tickethubacr2026.azurecr.io/tickethub-frontend
    tag: 0e67f618e64b77d6d4e87022a1bb88c61f644f5b
    pullPolicy: Always
  service:
    type: ClusterIP
    port: 80
  resources:
    requests:
      cpu: "50m"
      memory: "64Mi"
    limits:
      cpu: "150m"
      memory: "128Mi"
  probes:
    liveness:
      path: /
      initialDelaySeconds: 15
      periodSeconds: 10
    readiness:
      path: /
      initialDelaySeconds: 10
      periodSeconds: 5
config:
  NODE_ENV: production
  PORT: "5000"
